theme: minimal-mistakes-jekyll
markdown: kramdown
# remote_theme: mmistakes/minimal-mistakes@4.17.2
minimal_mistakes_skin: "air" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
masthead_title: "Zongnan Bao's Website"
logo: assets/images/profile.png
search: true
title:  Zongnan Bao
github_username: bznick98

jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/"

plugins:
  - jekyll-relative-links
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed

defaults:
  # _posts
  - scope:
      path: ""
      type: pages
    values:
      author_profile: true
      layout: single
      read_time: false
      author:
        name: "Zongnan Bao"
        avatar: "/assets/images/profile.png"
        bio: "From Hangzhou China, study at University of Illinois Urbana-Champaign" # Note: Markdown is allowed
        links:
          - label: "Github"
            icon: "fab fa-github"
            url: "https://github.com/bznick98"
          - label: "Instagram"
            icon: "fab fa-twitter-square"
            url: "https://instagram.com/zbao98"
          - label: "500px"
            icon: "fab fa-500px"
            url: "https://500px.com/zbao98"

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
